version: '3.5'

networks:
  localdev:
    name: localdev

services:
  menu-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db-server
      - seq-interface
    restart: always
    networks:
      - localdev

  db-server:
    image: postgres
    container_name: postgres_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2348
    networks:
      - localdev

  seq-interface:
    image: datalust/seq:latest
    container_name: seq_logger
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5340:80"
      - "5341:5341"
    networks:
      - localdev
